### ISSUE TITLE
Re-organization?

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Rainbow-Code#127]
Is the code easy to find here based on the corresponding video? I'm open to any and all ideas for reorganizing this repo.

**Comment by MrFibunacci** [comment]
I by self found till now everything I Searched for! So I dont have anny problems.

(But due the amount of content its qute easy to lose overview.)

**Comment by SylannBin** [comment]
I'm not sure if it's any important to anyone but,
wouldn't it be better to have the p5 files in one place, instead of having them in almost every folders?
Apart from that, the naming is perfect, so no reorganization feels necessary.

**Comment by shiffman** [comment]
@SylannBin I agree in principle, however, because coders sometimes grab just one folder/example it's good for them to work "stand-alone." To reduce the clutter I could reference p5 via CDN in `index.html`.

**Comment by tirzatirza14** [comment]
Oh well, hope this is not too late but it took me a while to find the P5 tutorial folder that I wanted to check out because they're referred to differently here than on Youtube, title-wise. For instance, on Github, the folder to the video 9.5: Random Circles with No Overlap - p5.js Tutorial is called 9.5_p5.js_uniform_random_sampling. I figured they're the same thing after reading the description on YouTube, but I thought I'd bring this up lol.

**Comment by shiffman** [comment]
#347 takes care of this, we can open individual issues going forward!
